{{- include "ffc-helm-library.deployment" (list . "ffc-ahwr-defra-id-proxy.deployment") -}}
{{- define "ffc-ahwr-defra-id-proxy.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "ffc-helm-library.container" (list . "ffc-ahwr-defra-id-proxy.container") }}
{{- end -}}
