services:
  ffc-ahwr-defra-id-proxy:
    build:
      context: .
      target: production
    image: ffc-ahwr-defra-id-proxy
    container_name: ffc-ahwr-defra-id-proxy
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ahwr-defra-id-proxy-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
