apiVersion: v2
description: Proxy service to support defra id login on dynamic sandbox environments
name: ffc-ahwr-defra-id-proxy
# this version is automatically updated in the build pipeline
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: 4.0.0
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
