environment: production
environmentCode:
name: ffc-ahwr-defra-id-proxy
namespace: ffc-ahwr
workstream: ffc-ahwr
image: ffc-ahwr-defra-id-proxy

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-ahwr-defra-id-proxy-config-map

containerSecret:
  name: ffc-ahwr-defra-id-proxy-container-secret
  type: Opaque

deployment: {}

ingress:
  class: nginx
  endpoint: ffc-ahwr-defra-id-proxy
  server: example.com

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5
